# Global settings applied across all microservices
global:
  awsRegion: ap-south-1
  awsAccountId: "675789571925"
  s3Bucket: streamingapp-media-675789571925-ap-south-1
  imageRegistry: 675789571925.dkr.ecr.ap-south-1.amazonaws.com
  imageTag: latest
  imagePullPolicy: Always
  clientUrls: "http://localhost:3000,http://a58ecf898ca284bbf9056d00d934692a-1428735725.ap-south-1.elb.amazonaws.com,https://a58ecf898ca284bbf9056d00d934692a-1428735725.ap-south-1.elb.amazonaws.com"

# MongoDB Database Deployment
mongodb:
  enabled: true
  image: mongo:6.0
  port: 27017
  persistence:
    enabled: true
    storageClass: ebs-gp3-sc
    size: 5Gi
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

# Frontend (React 18 + NGINX SPA)
frontend:
  replicaCount: 2
  image: streamingapp-frontend
  port: 80
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 50

# Auth Microservice (Node.js / Express / JWT)
authService:
  replicaCount: 1
  image: streamingapp-auth
  port: 3001
  jwtSecret: "streamingapp-super-secret-jwt-key-2026"
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

# Streaming Microservice (Node.js / HLS / S3)
streamingService:
  replicaCount: 2
  image: streamingapp-streaming
  port: 3002
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 256Mi
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 6
    targetCPUUtilizationPercentage: 60

# Admin Microservice (Node.js / S3 Uploads)
adminService:
  replicaCount: 1
  image: streamingapp-admin
  port: 3003
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

# Chat Microservice (Node.js / Socket.IO)
chatService:
  replicaCount: 1
  image: streamingapp-chat
  port: 3004
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

# Ingress Controller Configuration
ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/websocket-services: "streaming-app-chat"
