{{- if .Values.frontend.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "streaming-app.fullname" . }}-frontend-hpa
  labels:
    {{- include "streaming-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "streaming-app.fullname" . }}-frontend
  minReplicas: {{ .Values.frontend.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.frontend.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.frontend.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
---
{{- if .Values.streamingService.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "streaming-app.fullname" . }}-streaming-hpa
  labels:
    {{- include "streaming-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: streaming
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "streaming-app.fullname" . }}-streaming
  minReplicas: {{ .Values.streamingService.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.streamingService.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.streamingService.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
