{{- if .Values.mongodb.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "streaming-app.fullname" . }}-mongodb
  labels:
    {{- include "streaming-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "streaming-app.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: mongodb
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "streaming-app.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: mongodb
    spec:
      containers:
        - name: mongodb
          image: {{ .Values.mongodb.image | quote }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: mongodb
              containerPort: {{ .Values.mongodb.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.mongodb.resources | nindent 12 }}
          volumeMounts:
            - name: mongodata
              mountPath: /data/db
      volumes:
        - name: mongodata
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "streaming-app.fullname" . }}-mongodb
  labels:
    {{- include "streaming-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.mongodb.port }}
      targetPort: mongodb
      protocol: TCP
      name: mongodb
  selector:
    app.kubernetes.io/name: {{ include "streaming-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: mongodb
{{- end }}
